id: P000380
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:36:59.121232
source_metadata:
  id: bdr:W1KG4230
  title: བདེ་མཆོག་ནམ་མཁའ་དང་མཉམ་པའི་རྒྱུད་ཀྱི་རྩ་འགྲེལ
  author: ''
  volumes:
    a8e5e3af4a2d46fe9fb31aebeb849cf3:
      image_group_id: I1PD97692
      title: Volume 1 of bde mchog nam mkha' dang mnyam pa'i rgyud kyi rtsa 'grel
      volume_number: 1
      total_pages: 68
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
